In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
slice_of_array = arr[0:5]

In [10]:
slice_of_array

array([100, 100, 100, 100, 100])

In [11]:
slice_of_array[:] = 99

In [12]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [14]:
slice_of_array = arr.copy()

In [15]:
slice_of_array[:] = 5

In [16]:
slice_of_array

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr = np.arange(0, 40, 5)

In [20]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35])

In [21]:
arr = np.arange(0, 45, 5)

In [22]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [23]:
arr.reshape(3,3)

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [24]:
arr

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40])

In [25]:
arr = arr.reshape(3,3)

In [26]:
arr

array([[ 0,  5, 10],
       [15, 20, 25],
       [30, 35, 40]])

In [27]:
arr[1,1]

20

In [28]:
arr[:2,1:]

array([[ 5, 10],
       [20, 25]])

In [29]:
arr[arr > 7]

array([10, 15, 20, 25, 30, 35, 40])