In [4]:
import numpy as np

In [5]:
np.random.randint(0, 100, 5)

array([22, 77, 72, 81, 21])

In [6]:
np.random.randint(0, 100, (5,5))

array([[34, 42, 39, 19, 18],
       [74, 43, 88, 64, 84],
       [60,  0, 58,  0, 27],
       [13, 84, 10, 44, 90],
       [ 9, 24, 38, 97, 51]])

In [9]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [10]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [12]:
arr = np.arange(0, 25)

In [13]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [15]:
arr.reshape(5, 4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [16]:
ranarr = np.random.randint(0, 101, 10)

In [17]:
randarr.max()

NameError: name 'randarr' is not defined

In [18]:
ranarr.max()

99

In [20]:
ranarr.min()

2

In [22]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [23]:
ranarr.argmax()

5

In [24]:
ranarr.argmin()

7

In [25]:
ranarr.dtype

dtype('int64')

In [26]:
ranarr.shape

(10,)

In [27]:
ranarr = ranarr.reshape(5, 5)

ValueError: cannot reshape array of size 10 into shape (5,5)

In [28]:
ranarr = ranarr.reshape(2, 5)

In [29]:
ranarr.shape

(2, 5)